name: AgroBTech
description: Gerador de laudos
publish_to: "none"
version: 1.0.0+1




flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf
       


environment:
  sdk: ">=3.1.3 <3.19.2"



dependencies:
  path_provider: ^2.1.2 
  file_picker: ^8.0.0+1 
  provider: ^6.1.2
  pdf: ^3.10.8
  share: ^2.0.4
  

  
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

